version: 1
projects:
  conjure:
    output-dir: ./conjure
    ir-locator: https://repo1.maven.org/maven2/com/palantir/witchcraft/api/witchcraft-health-api/1.3.0/witchcraft-health-api-1.3.0.conjure.json
